### ISSUE TITLE
crear modules

### ISSUE THREAD

**Issue by hscordonez1810** [Yavirac-edu/backend-tendencias#3]
![image](https://user-images.githubusercontent.com/77408888/214984484-cd8aa800-6320-47b5-b436-2b686f6f2d5a.png)

**Comment by grmvera** [comment]
npm i --save @nestjs/typeorm typeorm

**Comment by grmvera** [comment]
npm install class-validator --save

**Comment by grmvera** [comment]
import { isNotEmptyValidationOpntions, IsStringValidationOpntions } from '@shared/validation'
